### ISSUE TITLE
Is there a paper for this project?

### ISSUE THREAD

**Issue by sonigeez** [showlab/ShowUI#1]
hey, really interested in this project, was wondering if there’s a research paper or publication related to it. If so, could you share a link or some details?
Thanks in advance!

**Comment by QinghongLin** [comment]
Hi, @sonigeez 
Yes, we have a research paper for this project, which will be released very soon :)

**Comment by QinghongLin** [comment]
@sonigeez Hi, the paper is available at arXiv: https://arxiv.org/abs/2411.17465.
