### ISSUE TITLE
`torch` should be added in `requirements.txt` or annotated in `README.md`

### ISSUE THREAD

**Issue by AkagawaTsurunaki** [showlab/ShowUI#10]
`deepspeed` requires `torch` to be installed in advance, otherwise a build error will occur when running the `pip` command.

It was just a harmless minor issue and I successfully ran your project on an Ubuntu system.

**Comment by QinghongLin** [comment]
Sorry for mistakes, I will fix it.

**Comment by QinghongLin** [comment]
Hi @AkagawaTsurunaki  I have updated, and make the requirement being more easy.
