### ISSUE TITLE
Uncertainty in Agent Termination Due to Missing "Complete Action" in Action Space

### ISSUE THREAD

**Issue by DaeHwanGi** [showlab/ShowUI#14]
## Issue Description

In the example provided in the README, the GUI Agent’s action space does not include a “Complete Action,” making it unclear when the agent should terminate. Occasionally, the agent seems to enter an internal loop, possibly due to the missing “Complete Action” or incorrect input handling.

Below is the input structure I am using:
```python
messages = [
    {
        "role": "user",
        "content": [
            {"type": "text", "text": system_prompt},
            {"type": "text", "text": f'Task: {query}'},
            {"type": "image"}, # previous screenshot
            {"type": "text", "text": "action result 1"},
            {"type": "text", "text": "action result 2"},
            {"type": "image"}, # current screenshot
        ],
    }
]

text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True,
)

image_0 = Image.open("./examples/1.png")
image_1 = Image.open("./examples/2.png")

inputs = processor(
    text=[text],
    images=[image_0, image_1],
    padding=True,
    return_tensors="pt",
)
inputs = inputs.to("cuda")
# ...
```

### Questions
1. Is the above input structure correct for this model?
2. The model was trained with interleaved data, but is it appropriate to use only a single image for input?
3. Are there any additional configurations required to prevent the agent from entering an internal loop?
4. What was the list of actions during training dataset?

### Attempted Fix

I added “Complete Action” to the action space, but it did not resolve the issue.
```
1. `CLICK`: Click on an element, value is not applicable and the position [x,y] is required. 
5. `INPUT`: Type a string into an element, value is a string to type and the position [x,y] is required. 
6. `SELECT`: Select a value for an element, value is not applicable and the position [x,y] is required. 
7. `HOVER`: Hover on an element, value is not applicable and the position [x,y] is required.
8. `ANSWER`: Answer the question, value is the answer and the position is not applicable.
9. `ENTER`: Enter operation, value and position are not applicable.
10. `SCROLL`: Scroll the screen, value is the direction to scroll and the position is not applicable.
11. `SELECT_TEXT`: Select some text content, value is not applicable and position [[x1,y1], [x2,y2]] is the start and end position of the select operation.
12. `COPY`: Copy the text, value is the text to copy and the position is not applicable.
13. `STATUS TASK COMPLETE`: Indicates that the task was successfully completed, value and position are not applicable.
14. `STATUS TASK IMPOSSIBLE`: Indicates that the task could not be completed due to constraints or other issues, value and position are not applicable.
```

**Comment by QinghongLin** [comment]
Hi @DaeHwanGi ,

Thanks for your deep interest in our work!

For 1: Please refer this issue: https://github.com/showlab/ShowUI/issues/5
For 2: Yes, it is available. As single image is a special case of the interleaved sequence (with len=1)
For 3: Please try 1, if still suffer, let us think what happen.
For 4: For the training dataset action list, it depends, such as PC, Web, Mobile are different, sometimes we might have customized action.

**Comment by Han1018** [comment]
Hi @DaeHwanGi ,
I noticed the issue you raised regarding model do not have  "Complete Action". I was wondering if it has been resolved or if you're still encountering the problem.

**Comment by DaeHwanGi** [comment]
> Hi @DaeHwanGi ,
> 
> Thanks for your deep interest in our work!
> 
> For 1: Please refer this issue: #5 For 2: Yes, it is available. As single image is a special case of the interleaved sequence (with len=1) For 3: Please try 1, if still suffer, let us think what happen. For 4: For the training dataset action list, it depends, such as PC, Web, Mobile are different, sometimes we might have customized action.

Thank you for your response. In issue #5, it seems that the past action is placed before the image. However, based on my reading of the paper, I understood that the action at time t should appear after the image at time t. I’m not entirely sure which interpretation is correct. If possible, could you provide a simple example that includes the added past action? It would help clarify how these elements should be represented.

Additionally, I remain uncertain about how to determine when a task is considered complete in a real-world setting if there is no explicit “complete” action. I had hoped that carefully adjusting the prompts would enable the model to generalize more effectively across various platforms, but this does not appear to be producing the intended results.

**Comment by DaeHwanGi** [comment]
> Hi @DaeHwanGi , I noticed the issue you raised regarding model do not have "Complete Action". I was wondering if it has been resolved by updating prompt or if you're still encountering the problem.

HI @Han1018. I have not observed any new actions being added to the results solely by modifying the prompt. My guess is that this issue might stem from a mismatch between the trained data and the prompt, or possibly because the model is too small and lacks sufficient generalization capability.

**Comment by QinghongLin** [comment]
@DaeHwanGi  This is one limitation by our model, as our model so far being small scale, and the navigation data not being very generalize. We will continue improve our local model.

BTW, I might suggest that you try our solution here : https://github.com/showlab/computer_use_ootb?tab=readme-ov-file
which connects GPT-4o as planner with ShowUI as actor.

It is more reliable to determine the end of task.
