### ISSUE TITLE
Testing Results on Mind2Web Dataset

### ISSUE THREAD

**Issue by mrswang1** [showlab/ShowUI#16]
I have conducted tests using open-source models and prompts on the Mind2Web dataset. However, the results differ significantly from those presented in the paper. Could you please help me understand what might be the reasons for this discrepancy?

**Comment by QinghongLin** [comment]
@mrswang1 Hi I think I have reply to you in the wechat group.

We need to ensure the action space is customized for the Mind2Web (3 actions) so that to align the benchmark setting.
I will release these code and details in next phrase.
