### ISSUE TITLE
How can I generate the training JSON 

### ISSUE THREAD

**Issue by yunh-w** [showlab/ShowUI#17]
How can I generate the training JSON with these data? Thanks.
![image](https://github.com/user-attachments/assets/f8ddb191-011a-4ac5-8b9c-3faf965e6c25)

**Comment by QinghongLin** [comment]
Hi @yunh-w , 

I have uploaded the training metadata json in https://huggingface.co/datasets/showlab/ShowUI-desktop-8K/tree/main/metadata

The training code will be available soon. :)
