### ISSUE TITLE
iterative refinement

### ISSUE THREAD

**Issue by RainPot** [showlab/ShowUI#18]
效果很棒！
请问本地使用模型时，如何使用 iterative refinement 功能呢？

**Comment by h-siyuan** [comment]
We will add the iterative grounding feature to local run, stay tuned:)

**Comment by QinghongLin** [comment]
@RainPot  Hi Thanks for your interest, you can first refer this page for iterative grounding implementation.

https://huggingface.co/spaces/showlab/ShowUI/blob/main/app.py#L93
