### ISSUE TITLE
Request for Reproducible Evaluation Script for ShowUI/ShowUI-G on Screenspot Dataset

### ISSUE THREAD

**Issue by aptsunny** [showlab/ShowUI#19]
![image](https://github.com/user-attachments/assets/e9802995-fb83-44bf-a6ea-ef0ba13c7434)

Inquire about the recent results presented in your paper regarding the zero-shot grounding capabilities of ShowUI and ShowUI-G on the Screenspot dataset.

I am particularly impressed by the strong grounding results that ShowUI has achieved with a lightweight model size and minimal training data, as noted in Table 2 of the paper.  I believe that these findings could be very beneficial for the community if they can be independently verified and reproduced.

To facilitate this, I was wondering if your team could provide a script that outlines the exact evaluation process used for assessing ShowUI and ShowUI-G on the Screenspot dataset?  An open-source script would allow other researchers and practitioners to understand the methodology in depth and potentially reproduce the results within their own environments.

**Comment by QinghongLin** [comment]
Hi @aptsunny 
Thanks for comments,
Yes, we are working with clean these train / eval codes.

**Comment by QinghongLin** [comment]
@aptsunny 
Hi, we have upload the screenspot evaluation code at `main/eval_screenspot.py`, you can run train.py by providing our resume checkpoint with `--eval_only`
