### ISSUE TITLE
Have ShowUI work on NPUs

### ISSUE THREAD

**Issue by khairm** [showlab/ShowUI#21]
Given the increasing prevalence of NPUs for Windows AI computers. Could ShowUI be modified to use those instead of CUDA?

**Comment by QinghongLin** [comment]
@khairm Thanks for comments, I am not sure as I am not familiar with NPU.

But I have found a post about how to run huggingface LLM on NPU: https://huggingface.co/blog/bconsolvo/llava-gemma-2b-aipc-npu.

As our model is also integrated into huggingface codebase.

I think you can try to refer this :)

**Comment by khairm** [comment]
Hi, 

The repo specifies that CUDA is a requirement... Which I believe is NVIDIA only

A Neural Processing Unit (NPU) is a specialized computer chip that's designed to speed up artificial intelligence (AI) tasks, such as those involving.

New Intel, AMD and Qualcomm processors now have these alongside the usual CPUs and GPUs.
