### ISSUE TITLE
Have ShowUI work on non CUDA computers

### ISSUE THREAD

**Issue by khairm** [showlab/ShowUI#22]
The new Qualcomm, Intel and AMD chips have NPUs (instead of GPUs) specialised for AI workflows.

Could ShowUI also run on these?

**Comment by QinghongLin** [comment]
Dear @khairm  Thanks for your interesting!

Actually I have no experience on NPUs, I am sorry I am not able to answer this question.

But I found some repo which runs LLaVA on NPU, which might be helpful :)

https://github.com/zkyredstart/LLaVA-NPU
https://github.com/haotian-liu/LLaVA/pull/1446/files
