### ISSUE TITLE
Updated Example

### ISSUE THREAD

**Issue by chadhietala** [showlab/ShowUI#24]
I noticed that there is now [library code](https://github.com/showlab/ShowUI/tree/main/showui) for the ShowUI pre-processor and Qwen configuration.  I tried swapping out the default `AutoProcessor` for `ShowUIProcessor` but couldn't figure out why I was getting an image token / features  misalignment.

```
Dec 20, 15:54:57 | DEBUG | raise ValueError(
Dec 20, 15:54:57 | DEBUG | ValueError: Image features and image tokens do not match: tokens: 945, features 1890
```

Is it possible to document the purpose of these classes and potentially have a working example either in this repo or use them in computer_use repo? 

For context, I'm trying to understand why in some cases the model takes certain actions by getting the UI Graph screenshots and then seeing if there any hyperparameters that can be adjusted for my use case. These classes seem to expose the hyperparameters.

**Comment by QinghongLin** [comment]
Dear @chadhietala , I just fix a bug regarding this inconsistent token number, now should be able to work. :) thanks for let me know.

**Comment by QinghongLin** [comment]
@chadhietala 

Hi We have release the inference codes for visual token selection: https://github.com/showlab/ShowUI/blob/main/test.ipynb
Please take a try and have fun.
