### ISSUE TITLE
whereis dset_shared_navigation.py

### ISSUE THREAD

**Issue by cugb1004101218** [showlab/ShowUI#25]
can't found the py file
Thank you

**Comment by QinghongLin** [comment]
@cugb1004101218 Hi I will update the navigation part soon.

**Comment by cugb1004101218** [comment]
Orz膜拜大佬，非常感谢

**Comment by QinghongLin** [comment]
Hi @cugb1004101218 , 我上传了dset_shared_navigation.py和data/template/aitw.py，您可以先参考一下这部份的实现，我们会在接下来更新navigation部分的训练tutorial；
目前grounding部分的tutorial已经相对完整了。
