### ISSUE TITLE
PC端的使用实例，以及执行动作有介绍吗

### ISSUE THREAD

**Issue by RoninBang** [showlab/ShowUI#26]
我想测试PC端实现一些代理动作，但是我发现Click 无法区分单击操作双击操作，照成一些软件无法打开，请问有具体的PC端操作动作以及推理示例吗

**Comment by QinghongLin** [comment]
@RoninBang Hi Thanks for your interest. So far our training data do not introduce double click and lack of PC navigation data, so it will be hard to generalize to these actions.

For PC usage, one suggested way is followed here -- [OOTB](https://github.com/showlab/computer_use_ootb?tab=readme-ov-file) a more reliable combination agent with an additional planner
