### ISSUE TITLE
train detail

### ISSUE THREAD

**Issue by 2877992943** [showlab/ShowUI#27]
Hi ,fantastic work ,appreciate your great job!
may I ask 2 question concerning the training detail which I have not find answers reading your paper.

1)In section B.1 it says instruciton-tune and downstream-task. does it mean there is 2 finetune stage, first you finetune base model on instruction-tune data(table1) and then your finetune the model on downstream task such as mind2web. Am  I interprete correctly?

2)in table 3,4,5, it mention a showui-zs(not FT), what does it mean not FT? does it mean neither finetune on instruction-tune data not on downstream task like mind2web? Hope you can correct me if I misunderstand.

looking forward your answers for the above 2 question. thks

**Comment by QinghongLin** [comment]
@2877992943 
Hi Thanks for your interest.
1. Yes, you are correct.
2. For zero-shot results, it means after SFT stage, we do not use the downstream mind2web for continuing ft, we just directly perform evaluation with SFT weights.

Hope my clarification can address your concerns.
