### ISSUE TITLE
fail to reproduce qwenVL demo

### ISSUE THREAD

**Issue by 2877992943** [showlab/ShowUI#28]
Hi,really appreciate that you provide  demo below. Very helpful to understand your work. However I cannot exactly get the same result.
https://github.com/showlab/ShowUI/blob/main/test.ipynb

below is what I get 

> (a) Screenshot patch number: 1296
(b) By applying UI-graph, UI Component number: 167
(c) Model output with skip ratio: 1
<|im_end|>

seems that failing to get 
>"The image shows the Google logo, which is a blue and yellow logo with the word "Google" written in white. The background of the image is white, and the logo is centered in the middle of the image.<|im_end|>" in your demo.

and below is my enviroment
torch=2.3.0
transformers=4.47.0
NVIDIA3090
cuda-12.2
hope to get some help.thks

**Comment by QinghongLin** [comment]
@2877992943  Hi can you please try to set the skip ratio as 0 and see what happens for the output.

Below is how I set up my environment.
```
conda create -n showui python=3.10
conda activate showui
pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118 --user
pip install -r requirements.txt --user
```
