### ISSUE TITLE
训练代码是不是还没弄好

### ISSUE THREAD

**Issue by cbigeyes** [showlab/ShowUI#29]
比如hf_screenspot.py、hf_mind2web.py

**Comment by cbigeyes** [comment]
在项目中没有找到这些脚本

**Comment by QinghongLin** [comment]
@cbigeyes hf_screenspot.py这些不需要了，我们hf上传的已经整理好了；
training code 现在支持grounding training；我们还在整理navigation的部分，请再等待一下

**Comment by QinghongLin** [comment]
@cbigeyes 我们更新了我们最新的训练代码，请您尝试一下哈
