### ISSUE TITLE
HF demo的精度比本地运行要高，导致本地模型的小图标定位能力变弱

### ISSUE THREAD

**Issue by truebit** [showlab/ShowUI#31]
非常感谢ShowLab开源ShowUI。Visual Grounding能力很出色。
不过我在本地部署模型后，发现同样的图片，本地部署的模型和[HF demo](https://huggingface.co/spaces/showlab/ShowUI)中比起来，结果要差0.01。导致一些小图标的定位能力有所欠缺。
请问问题出在哪里呢？

#### 测试图片：
<img width="443" alt="截屏2024-12-27 14 38 19" src="https://github.com/user-attachments/assets/b5f2a160-b72e-49ba-ba67-d5da17d384f5" />

#### 测试文本：
`Trash icon next to Recent Searches`

#### 测试结果：
* HF demo：
  * 返回文本：`[0.94, 0.16]`
  * 图片坐标示例：![hfdemo](https://github.com/user-attachments/assets/bcf661ba-8a7c-468d-8e86-51e4f57625ec)
 
* 本地结果：
  * 返回文本：`[0.94, 0.15]`
  * 图片坐标示例：![localdemo](https://github.com/user-attachments/assets/ecee94ff-e9a2-43ea-b5cf-025359fef873)

**Comment by QinghongLin** [comment]
@truebit , 谢谢您的兴趣和细心比较

我猜测一个原因在于
transformers version，qwen2vl在不同transformer下对position embed的处理有一些细微的差别，您可以比较您本地的版本是否和space下的version一致；

**Comment by truebit** [comment]
@QinghongLin 感谢大佬回复。不过spaces的requirements.txt文件中并没有指定transformers版本，请问从哪可以获知其使用的版本呢？

**Comment by truebit** [comment]
I just duplicated the spaces demo, it uses `transformers-4.47.1-py3-none-any.whl`, is this the verison you built 18days ago? 
Thanks @h-siyuan

**Comment by truebit** [comment]
`transformers=4.47.0` fixed the issue. I think we should pin this version in requirements.txt

**Comment by QinghongLin** [comment]
@truebit thanks! Yes, we have indicated the `4.47.0` in our requirements.txt
