### ISSUE TITLE
很好的工作！想请教些问题

### ISSUE THREAD

**Issue by positive666** [showlab/ShowUI#9]
1.直接用QWEN2VL去自己设计标注SFT的嘛？
2.多步的GUI agent执行 训练上有什么思路嘛？

**Comment by QinghongLin** [comment]
@positive666 Hi 
第一个问题不太清楚, 您是指用Qwen2VL来给数据打标吗？
第二个问题我们在paper的sec Interleaved VLA streaming里介绍我们的思考哈; 
另外您可以加入微信群，直接在群里提问 :)

**Comment by positive666** [comment]
> @positive666 Hi 第一个问题不太清楚, 您是指用Qwen2VL来给数据打标吗？ 第二个问题我们在paper的sec Interleaved VLA streaming里介绍我们的思考哈; 另外您可以加入微信群，直接在群里提问 :)
好的 感谢回复 我正在读paper，第一个问题是我看Base是QWEN2VL，这个模型可以直接用来训练box\points类grounding的数据嘛？

**Comment by QinghongLin** [comment]
@positive666 是的，QWEN2VL可以直接训练box\points类grounding的数据

**Comment by QinghongLin** [comment]
@positive666 可以在群里直接问的哈

**Comment by ecccccsgo** [comment]
@QinghongLin 你好，请问怎么加群呢？想了解一下最新进展 :)

**Comment by hhxxttxsh** [comment]
求加群讨论，谢谢！
